// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHN1bgfn5RZ1BJhKkeANVwnR4IVRkezQo',
    appId: '1:373943872282:web:237a9f5bcc634baa795aa3',
    messagingSenderId: '373943872282',
    projectId: 'socio-care',
    authDomain: 'socio-care.firebaseapp.com',
    storageBucket: 'socio-care.firebasestorage.app',
    measurementId: 'G-C5WB9FE19R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_kgtIoWM10pmEfJd8TUBFwOcQL19BjBM',
    appId: '1:373943872282:android:58535f706287eb04795aa3',
    messagingSenderId: '373943872282',
    projectId: 'socio-care',
    storageBucket: 'socio-care.firebasestorage.app',
  );
}
